nginx:
  build: ./nginx
  restart: always
  links:
    - web1:web1
    - web2:web2
  ports:
    - "80:80"

web1:
  image: iic2173grupo2/news-api
  restart: always
  environment:
    - ENVIRONMENT=PRODUCTION
    - AUTH=ENABLE
    - SECRET_HASH
    - NEO4J_HOST
    - NEO4J_PORT
    - NEO4J_USER
    - NEO4J_PASS

web2:
  image: iic2173grupo2/news-api
  restart: always
  environment:
    - ENVIRONMENT=PRODUCTION
    - AUTH=ENABLE
    - SECRET_HASH
    - NEO4J_HOST
    - NEO4J_PORT
    - NEO4J_USER
    - NEO4J_PASS

newrelic:
  extends:
    file: ./../analytics.yml
    service: newrelic
  environment:
    - NEW_RELIC_LICENSE_KEY
