web:
  image: iic2173grupo2/news-api
  restart: always
  ports:
    - "80:8000"
  environment:
    - ENVIRONMENT=PRODUCTION
    - AUTH=ENABLE
    - SECRET_HASH
    - NEO4J_HOST
    - NEO4J_PORT
    - NEO4J_USER
    - NEO4J_PASS

newrelic:
  extends:
    file: ./../analytics.yml
    service: newrelic
  environment:
    - NEW_RELIC_LICENSE_KEY
