lb:
  image: tutum/haproxy
  ports:
    - "80:80"
  links:
    - web

db:
  image: postgres

web:
  image: iic2173grupo2/news-api
  restart: always
  links:
    - db
  environment:
    - ENVIRONMENT=PRODUCTION
    - AUTH=ENABLE
    - SECRET_HASH
    - NEO4J_HOST
    - NEO4J_PORT
    - NEO4J_USER
    - NEO4J_PASS
    - LOADER_IO_TOKEN
    - ANALYTICS_TOKEN

newrelic:
  extends:
    file: ./../analytics.yml
    service: newrelic
  environment:
    - NEW_RELIC_LICENSE_KEY
