neo4j:
  image: neo4j
  restart: always
  privileged: true
  ports:
    - "80:7474"
  environment:
    - NEO4J_AUTH
  cap_add:
    - SYS_RESOURCE

newrelic:
  extends:
    file: ./../analytics.yml
    service: newrelic
  environment:
    - NEW_RELIC_LICENSE_KEY
    - NEO4J_CACHE_MEMORY=4G
