lb:
  image: tutum/haproxy
  ports:
    - "80:80"
  links:
    - analyzer

analyzer:
  image: iic2173grupo2/analyzer2
  environment:
    - NEO4J_HOST
    - NEO4J_PORT
    - NEO4J_USER
    - NEO4J_PASS

newrelic:
  extends:
    file: ./../analytics.yml
    service: newrelic
  environment:
    - NEW_RELIC_LICENSE_KEY
