lb:
  image: tutum/haproxy
  ports:
    - "80"
  links:
    - analyzer

analyzer:
  image: iic2173grupo2/analyzer2
  environment:
    - ENV=production

newrelic:
  extends:
    file: ./../analytics.yml
    service: newrelic
  environment:
    - NEW_RELIC_LICENSE_KEY
