nginx:
  build: ./nginx
  restart: always
  links:
    - local:local
  ports:
    - "80:80"

local:
  image: iic2173grupo2/analyzer2
  ports:
    - "8080:8080"
  command: mvn exec:java
  environment:
    - NEO4J_HOST
    - NEO4J_PORT
    - NEO4J_USER
    - NEO4J_PASS

newrelic:
  extends:
    file: ./../analytics.yml
    service: newrelic
  environment:
    - NEW_RELIC_LICENSE_KEY
